pipeline {
  agent any
  stages {
    stage('Clone') {
      steps {
        checkout scm
      }
    }
    stage('Install & Build') {
      steps {
        sh 'npm install'
        sh 'npm run build'
      }
    }
    stage('Docker Build') {
      steps {
        sh 'docker build -t game-frontend .'
      }
    }
    stage('Run') {
      steps {
        sh 'docker run -d -p 3000:3000 game-frontend'
      }
    }
  }
}
