pipeline {
  agent any
  stages {
    stage('Clone') {
      steps {
        checkout scm
      }
    }
    stage('Build Backend Image') {
      steps {
        sh 'docker build -t game-backend .'
      }
    }
    stage('Start Mongo Cluster') {
      steps {
        sh 'docker-compose -f docker-compose.yml up -d'
        sh 'sleep 10'
        sh '''
        docker exec -i game-catalog-mongo1-1 mongosh <<EOF
        rs.initiate({
          _id: "rs0",
          members: [
            { _id: 0, host: "mongo1:27017" },
            { _id: 1, host: "mongo2:27017" },
            { _id: 2, host: "mongo3:27017" }
          ]
        })
        EOF
        '''
      }
    }
    stage('Run Backend') {
      steps {
        sh 'docker run -d -p 5000:5000 --env-file .env game-backend'
      }
    }
  }
}
